# Generated by Django 4.1.3 on 2022-12-06 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafeteria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('clasificacion', models.CharField(max_length=30)),
                ('nombre_del_producto', models.CharField(max_length=30)),
                ('precio', models.IntegerField()),
                ('image', models.CharField(max_length=150)),
                ('fecha_de_vencimiento', models.CharField(max_length=30)),
                ('fecha_de_expedicion', models.CharField(max_length=30)),
            ],
        ),
    ]
